# Generated by Django 5.0.1 on 2024-01-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Romances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='SubTítulo')),
                ('content', models.TextField(verbose_name='Descipción')),
                ('image', models.ImageField(upload_to='romance', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Poema de Romance',
                'verbose_name_plural': 'Poemas de Romance',
                'ordering': ['-created'],
            },
        ),
    ]
