# Generated by Django 5.0.1 on 2024-01-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='SubTítulo')),
                ('content', models.TextField(verbose_name='Descipción')),
                ('image', models.ImageField(upload_to='amores', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'poema_de_Amor',
                'verbose_name_plural': 'poemas_de_Amor',
                'ordering': ['-created'],
            },
        ),
    ]
