# Generated by Django 5.0.1 on 2024-01-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amores',
            options={'ordering': ['-created'], 'verbose_name': 'Poema de Amor', 'verbose_name_plural': 'poemas de Amor'},
        ),
        migrations.AlterField(
            model_name='amores',
            name='image',
            field=models.ImageField(upload_to='amor', verbose_name='Imagen'),
        ),
    ]
