# Generated by Django 5.0.1 on 2024-01-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'poema', 'verbose_name_plural': 'poemas'},
        ),
    ]
