# Generated by Django 5.0.1 on 2024-01-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Descipción')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('clasification', models.CharField(max_length=100, verbose_name='Clasificación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Clasificación de Autor y Poema',
                'verbose_name_plural': 'Clasificación de Autores y Poemas',
                'ordering': ['-created'],
            },
        ),
    ]
